// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_qrismb_RCPPEXPORTS_H_GEN_
#define RCPP_qrismb_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace qrismb {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("qrismb", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("qrismb", "_qrismb_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in qrismb");
            }
        }
    }

    inline arma::mat Amat(arma::vec b, arma::mat X, arma::vec W_star, arma::mat H, arma::vec E, arma::vec I, arma::vec logT, double Q) {
        typedef SEXP(*Ptr_Amat)(SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP,SEXP);
        static Ptr_Amat p_Amat = NULL;
        if (p_Amat == NULL) {
            validateSignature("arma::mat(*Amat)(arma::vec,arma::mat,arma::vec,arma::mat,arma::vec,arma::vec,arma::vec,double)");
            p_Amat = (Ptr_Amat)R_GetCCallable("qrismb", "_qrismb_Amat");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_Amat(Shield<SEXP>(Rcpp::wrap(b)), Shield<SEXP>(Rcpp::wrap(X)), Shield<SEXP>(Rcpp::wrap(W_star)), Shield<SEXP>(Rcpp::wrap(H)), Shield<SEXP>(Rcpp::wrap(E)), Shield<SEXP>(Rcpp::wrap(I)), Shield<SEXP>(Rcpp::wrap(logT)), Shield<SEXP>(Rcpp::wrap(Q)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

}

#endif // RCPP_qrismb_RCPPEXPORTS_H_GEN_
