# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
Amat <- function(b, X, W_star, H, I, logT, Q) {
    .Call('_qris_Amat', PACKAGE = 'qris', b, X, W_star, H, I, logT, Q)
}

#' @noRd
isObj <- function(b, X, W, H, I, logT, Q) {
    .Call('_qris_isObj', PACKAGE = 'qris', b, X, W, H, I, logT, Q)
}

#' @noRd
isObjL <- function(b, X, W, H, I, logT, Q) {
    .Call('_qris_isObjL', PACKAGE = 'qris', b, X, W, H, I, logT, Q)
}

#' @noRd
rev_isObj <- function(b, X, W, H, E, I, logT, Q) {
    .Call('_qris_rev_isObj', PACKAGE = 'qris', b, X, W, H, E, I, logT, Q)
}

