# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Amat <- function(b, X, W_star, H, E, I, logT, Q) {
    .Call('_qrismb_Amat', PACKAGE = 'qrismb', b, X, W_star, H, E, I, logT, Q)
}

isObj <- function(b, X, W, H, I, logT, Q) {
    .Call('_qrismb_isObj', PACKAGE = 'qrismb', b, X, W, H, I, logT, Q)
}

rev_isObj <- function(b, X, W, H, E, I, logT, Q) {
    .Call('_qrismb_rev_isObj', PACKAGE = 'qrismb', b, X, W, H, E, I, logT, Q)
}

